name: tycoon
description: A new Flutter project.
  
publish_to: 'none'   
  
version: 1.0.0+6

environment:
  sdk: ">=2.16.1 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.0
  flutter_launcher_icons: ^0.9.0
  cached_network_image: ^3.0.0
  flutter_bloc: ^8.0.1
  dio: ^4.0.0
  flutter_facebook_auth: ^4.1.1
  google_sign_in: ^5.3.0
  sign_in_with_apple: ^3.0.0
  sqflite: any
  shimmer: ^2.0.0
  flutter_staggered_grid_view: ^0.6.1
  pull_to_refresh: ^2.0.0
  flutter_secure_storage: ^5.0.2
  flutter_html: ^2.0.0
  url_launcher: ^6.0.0
  shared_preferences: ^2.0.6
  font_awesome_flutter: ^10.1.0
  firebase_core: ^1.3.0
  firebase_messaging: ^11.2.8
  flutter_local_notifications: ^9.4.0
  dropdown_search: ^3.0.1
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  simple_animations: ^4.0.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  
flutter:    
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/home/
    - assets/locale/
    
    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
